name: Calendar Anaïs update

on:
  schedule:
  - cron: "0 0 * * *" # At the end of every day

  workflow_dispatch:  # workflow_dispatch = can be triggered manually
    # Inputs the workflow accepts.
    inputs:
      YEAR_REQUEST:
        description: 'Requested year'
        default: '2026'
        required: true

jobs:
  runner_anais:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        env: # Or as an environment variable
          CI_PROJECT_ID: ${{ secrets.CI_PROJECT_ID }}
          CI_PRIVATE_KEY_ID: ${{ secrets.CI_PRIVATE_KEY_ID }}
          CI_PRIVATE_KEY: ${{ secrets.CI_PRIVATE_KEY }}
          CI_CLIENT_EMAIL: ${{ secrets.CI_CLIENT_EMAIL }}
          CI_CLIENT_ID: ${{ secrets.CI_CLIENT_ID }}
          CI_CLIENT_X509_CERT_URL: ${{ secrets.CI_CLIENT_X509_CERT_URL }}
        run: |
          python app.py "${{ github.event.inputs.YEAR_REQUEST }}" "0" "Anaïs"
